extensions:
  developer:
    display_name: null
    enabled: true
    name: developer
    timeout: null
    type: builtin
  mcpgateway:
    bundled: false
    description: 'Docker MCP gateway'
    enabled: true
    name: mcpgateway
    timeout: 300
    type: sse
    uri: http://mcp-gateway:8811/sse
keyring: false

GOOSE_CLI_MIN_PRIORITY: 0.8
GOOSE_MODE: auto
GOOSE_PROVIDER: openai
GOOSE_ROUTER_TOOL_SELECTION_STRATEGY: default

OPENAI_BASE_PATH: engines/llama.cpp/v1/chat/completions
OPENAI_HOST: http://model-runner.docker.internal

